import type { Metadata } from "next";
import { dark } from '@clerk/themes'
import { Geist, Geist_Mono } from "next/font/google";
import {
  ClerkProvider,
} from '@clerk/nextjs'
import "./globals.css";
import { checkUser } from "@/utils/CheckUser";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Barbasol",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const user = await checkUser()
    // console.log('user form layout', user)

  // async () => {
  // const Our_user = checkUser()
  // console.log(Our_user)
  // checkUser()

  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}>
      <html lang="en" suppressHydrationWarning>
      {/* <Script
        id="razorpay-checkout-js"
        src="https://checkout.razorpay.com/v1/checkout.js"
      /> */}
        <body
          className={`dark ${geistSans.variable} ${geistMono.variable} antialiased`}
          suppressHydrationWarning>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
