import type { Metadata } from "next";
import { dark } from '@clerk/themes'
import { Geist, Geist_Mono } from "next/font/google";
import {
  ClerkProvider,
} from '@clerk/nextjs'
import "./globals.css";
import { checkUser } from "@/utils/CheckUser";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Barbasol",
  description: "Generated by create next app",
};

// exporting Our_user
export const Our_user =  checkUser()

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // async () => {
    // export const user =  checkUser()
    // console.log('user form layout', user)
  // }

  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}>
      <html lang="en">
        <body
          className={`dark ${geistSans.variable} ${geistMono.variable} antialiased`}>
          {/* <SignedOut>
            <SignInButton />
          </SignedOut>
          <SignedIn>
            <UserButton />
          </SignedIn> */}
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
